apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: fastapi
  template:
    metadata:
      labels:
        component: fastapi
    spec:
      containers:
        - name: fastapi
          image: 'ghcr.io/tsadimas/myfastapi:latest'
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: fastapi-config
          imagePullPolicy: Always
      imagePullSecrets:
        - name: dockerconfigjson-github-com
